### ISSUE TITLE
When you create multiple areas in a map, the previously created ones disappear or even have no effect

### ISSUE THREAD

**Issue by WM9116** [Sarrus1/advanced-anticamp#1]
When you create multiple areas in a map, the previously created ones disappear or even have no effect,I hope you can answer it. Thank you!!!

**Comment by Sarrus1** [comment]
Hello, please make sure you hit "save" everytime you add a new zone.

**Comment by WM9116** [comment]
No, for example, after I created the first area in this diagram, there was no problem. Then I created a second area and saved it. After saving, I added "anticampboth" to the name of the file, and then reloaded it. At this time, the second area is visible, but the first area is lost,Thank you!!!

**Comment by Sarrus1** [comment]
I don't have my computer with me, but I'm 100% sure the plugin works, as it is running on my server.
To add the zones, follow these steps:

1. Type !campzones in chat.
2. Press 1 to add a new zone
3. Create the zone by pointing your mouse at the correct position.
4. Hit save!
5. Hit exit/previous.
6. Save again.
7. Go to edit zones.
8. Select the newly created zone.
9. Change its name.
10. Hit save.
11. Hit previous/exit.
12. Hit save again.
13. Reload.
14. Do the same with the next zone.

**Comment by WM9116** [comment]
OK, my problem seems to be solved. Thank you, because I have several servers using your plug-in, and several of my friends are also using it. They are very happy, but there is a problem. Can you put "sm_advancedanticamp_disabletime‘’ Set a "disable time" option, because we want to keep it on, but it seems to set it to a high time to achieve the purpose of always on, which will cause some bugs. For example, it seems that the second round will automatically close in a short time, so I hope you can set a closed option. Finally, thank you very much and wish you better and better!

**Comment by Sarrus1** [comment]
Hello,

Sorry I completely missed this.
Do you mean an option to make it "forever on"?
Like `sm_advancedanticamp_disabletime = 0` in order to make it always on, and not create a disable timer?

**Comment by Sarrus1** [comment]
Added this feature in d4ddacba06270e1f1fb15954b2d81aa8a13ff89b.
